language: generic
services:
  - docker

before_install:
  - docker build -t lucaslazzaris/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucaslazzaris/react-test npm test

after_success:
  - docker build -t lucaslazarris/multi-client ./client
  - docker build -t lucaslazarris/multi-nginx ./nginx
  - docker build -t lucaslazarris/multi-server ./server
  - docker build -t lucaslazarris/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucaslazzaris/multi-client
  - docker push lucaslazzaris/multi-nginx
  - docker push lucaslazzaris/multi-server
  - docker push lucaslazzaris/multi-worker